echo 'Vote, kMeans'
./clusterKMeansReduced.sh vote_pca_60.00.arff 2 3
./clusterKMeansReduced.sh vote_ica_60.00.arff 2 3
./clusterKMeansReduced.sh vote_rp_2.arff 2 3
./clusterKMeansReduced.sh vote_insig_60.00.arff 2 3
./clusterKMeansReduced.sh vote_pca_80.00.arff 2 3
./clusterKMeansReduced.sh vote_ica_80.00.arff 2 3
./clusterKMeansReduced.sh vote_rp_7.arff 2 3
./clusterKMeansReduced.sh vote_insig_80.00.arff 2 3
./clusterKMeansReduced.sh vote_pca_100.00.arff 2 3
./clusterKMeansReduced.sh vote_ica_100.00.arff 2 3
./clusterKMeansReduced.sh vote_rp_16.arff 2 3
./clusterKMeansReduced.sh vote_insig_100.00.arff 2 3
echo 'Segmentation, kMeans'
./clusterKMeansReduced.sh segmentation-train_pca_60.00.arff 7 8
./clusterKMeansReduced.sh segmentation-train_ica_60.00.arff 7 8
./clusterKMeansReduced.sh segmentation-train_rp_1.arff 7 8
./clusterKMeansReduced.sh segmentation-train_insig_60.00.arff 7 8
./clusterKMeansReduced.sh segmentation-train_pca_80.00.arff 7 8
./clusterKMeansReduced.sh segmentation-train_ica_80.00.arff 7 8
./clusterKMeansReduced.sh segmentation-train_rp_2.arff 7 8
./clusterKMeansReduced.sh segmentation-train_insig_80.00.arff 7 8
./clusterKMeansReduced.sh segmentation-train_pca_100.00.arff 7 8
./clusterKMeansReduced.sh segmentation-train_ica_100.00.arff 7 8
./clusterKMeansReduced.sh segmentation-train_rp_19.arff 7 8
./clusterKMeansReduced.sh segmentation-train_insig_100.00.arff 7 8
echo 'Vote, EM'
./clusterEMReduced.sh vote_pca_60.00.arff 2 1
./clusterEMReduced.sh vote_ica_60.00.arff 2 1
./clusterEMReduced.sh vote_rp_2.arff 2 1
./clusterEMReduced.sh vote_ica_60.00.arff 2 1
./clusterEMReduced.sh vote_pca_80.00.arff 2 1
./clusterEMReduced.sh vote_ica_80.00.arff 2 1
./clusterEMReduced.sh vote_rp_7.arff 2 1
./clusterEMReduced.sh vote_ica_80.00.arff 2 1
./clusterEMReduced.sh vote_pca_100.00.arff 2 1
./clusterEMReduced.sh vote_ica_100.00.arff 2 1
./clusterEMReduced.sh vote_rp_16.arff 2 1
./clusterEMReduced.sh vote_ica_100.00.arff 2 1
echo 'Segmentation, EM'
./clusterEMReduced.sh segmentation-train_pca_60.00.arff 7 4
./clusterEMReduced.sh segmentation-train_ica_60.00.arff 7 4
./clusterEMReduced.sh segmentation-train_rp_1.arff 7 4
./clusterEMReduced.sh segmentation-train_insig_60.00.arff 7 4
./clusterEMReduced.sh segmentation-train_pca_80.00.arff 7 4
./clusterEMReduced.sh segmentation-train_ica_80.00.arff 7 4
./clusterEMReduced.sh segmentation-train_rp_2.arff 7 4
./clusterEMReduced.sh segmentation-train_insig_80.00.arff 7 4
./clusterEMReduced.sh segmentation-train_pca_100.00.arff 7 4
./clusterEMReduced.sh segmentation-train_ica_100.00.arff 7 4
./clusterEMReduced.sh segmentation-train_rp_19.arff 7 4
./clusterEMReduced.sh segmentation-train_insig_100.00.arff 7 4
