./clusterKMeans.sh vote.arff 2 1
./clusterKMeans.sh vote.arff 2 2
./clusterKMeans.sh vote.arff 2 3
./clusterKMeans.sh vote.arff 2 4
./clusterKMeans.sh vote.arff 2 5
./clusterKMeans.sh vote.arff 2 8
./clusterKMeans.sh vote.arff 2 10
./clusterKMeans.sh segmentation-train.arff 7 1
./clusterKMeans.sh segmentation-train.arff 7 2
./clusterKMeans.sh segmentation-train.arff 7 3
./clusterKMeans.sh segmentation-train.arff 7 4
./clusterKMeans.sh segmentation-train.arff 7 5
./clusterKMeans.sh segmentation-train.arff 7 8
./clusterKMeans.sh segmentation-train.arff 7 10
./clusterEM.sh vote.arff 2 1
./clusterEM.sh vote.arff 2 2
./clusterEM.sh vote.arff 2 3
./clusterEM.sh vote.arff 2 4
./clusterEM.sh vote.arff 2 5
./clusterEM.sh vote.arff 2 8
./clusterEM.sh vote.arff 2 10
./clusterEM.sh segmentation-train.arff 7 1
./clusterEM.sh segmentation-train.arff 7 2
./clusterEM.sh segmentation-train.arff 7 3
./clusterEM.sh segmentation-train.arff 7 4
./clusterEM.sh segmentation-train.arff 7 5
./clusterEM.sh segmentation-train.arff 7 8
./clusterEM.sh segmentation-train.arff 7 10
